### PR TITLE
Knock back

### PR DESCRIPTION
**Pull request by daniellcurto**

### CODE REVIEW

**Review by mryindles — CHANGES_REQUESTED** [review]
This needs to include an actual coverage test of the code running, and proving that it works. I don't see any sort of coverage test code being included with this commit, nor do I see any further tasks, or user stories being advanced or completed, it looks like you just changed values you previously uploaded, those values need to be fetched, and actually applied to player objects.

**Review by MMercer8989 — APPROVED** [review]
Okay, I see what you are doing here and since your changes compile and everything runs fine I am giving you approval. That being said, I do have some changes that I would highly recommend you make before midnight. The first change is that you should make these knockback values between 1 and 2 (recall that these are going to be multiplied and so we don't want the values to be too large. subtle knockback is better). The second change is that you have created the function 'GetWeaponFeedback' however, you are only returning 0 every time it is called rather than the actual knockback values, I would recommend fetching the current weapons knockback value and returning that. If you need help with any of this I will be available through the rest of the day to assist, that being said you may want to message me in advance for some things.

**Review by MMercer8989 — APPROVED** [review]
thank you for making the changes, everything compiles and works fine.

**Review by mryindles — APPROVED** [review]
Thank you for revising this. Everything seems to be currently in order, everything compiles, and runs just fine, you have my approval

**Pull request merged**
