### PR TITLE
Removal of OpenTournamentEntry.umap for replacement

### PR DESCRIPTION
**Pull request by MMercer8989**
This file is being removed as it was committed in a compiled state and shouldn't have been, an unaltered replacement for this will be added in the next commit

### CODE REVIEW

**Review by mryindles — APPROVED** [review]
sounds good. Let's make sure to only ever commit things we know are correct so cleanups like this don't have to occur in the future.

**Comment by daniellcurto** [comment]
Yeah, we do not want any files that will potentially corrupt OpenTournament. Thank you for catching that Matt.

**Review by daniellcurto — COMMENTED** [review]
Yeah, we do not want any files that will potentially corrupt OpenTournament. Thank you for catching that Matt.

**Review by daniellcurto — APPROVED** [review]
Yeah, we do not want any files that will potentially corrupt OpenTournament. Thank you for catching that Matt.

**Pull request merged**
