### PR TITLE
UI customization

### PR DESCRIPTION
**Pull request by mryindles**
Changes made to the studio options menu. General layout design changes, as well as populating the menu with various assets to swap different UI elements between.  Rolling out to master as I want everyone to have the most current version of the menu to avoid any future conflicts the layout differences may cause as we work functionality into it.  Also updated the backlog in our group documentation here to include tasks from past sprints, as per project requirements.

### CODE REVIEW

**Comment by MMercer8989** [comment]
everything checks out in regard to your pull request. Good call on wanting to keep things up to date and consistent with the studio menu, in hindsight perhaps it would have been best if we were working on the menu in the same branch as to avoid potential conflicts. never the less, you have my approval here.

**Review by MMercer8989 — APPROVED** [review]
everything checks out in regard to your pull request. Good call on wanting to keep things up to date and consistent with the studio menu, in hindsight perhaps it would have been best if we were working on the menu in the same branch as to avoid potential conflicts. never the less, you have my approval here.

**Review by daniellcurto — APPROVED** [review]
Everything looks good. Looks like all tests have passed as these are uasset files.

**Comment by mryindles** [comment]
Having a bizzare issue with resolving file conflicts, I'm going to close this pull request and open up a new one

**Pull request closed without merging**
