### PR TITLE
Kill streaks

### PR DESCRIPTION
**Pull request by mryindles**
Finally finished messages for kill streaks, multikills, and shutdowns. Included test coverage, can send a screenshot of the test coverage in discord, or even include it with this pull request. Please view all changes, and leave a comment with whether or not you want test coverage screenshots in the repo, and of course, nice feedback on my code with whether or not I ought to make changes.

### CODE REVIEW

**Review by MMercer8989 — APPROVED** [review]
So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.

**Comment by mryindles** [comment]
> So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.

In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.

**Comment by MMercer8989** [comment]
> 
> 
> > So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.
> 
> In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.

Right, I saw the comment, I guess I was more wondering where 'AddDeath' is being called outside of the coverage tests. I'm assuming you would have called it when player is killed but I didn't see where you did that. Again, I could have just missed where you did that.

**Comment by mryindles** [comment]
> > > So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.
> > 
> > 
> > In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.
> 
> Right, I saw the comment, I guess I was more wondering where 'AddDeath' is being called outside of the coverage tests. I'm assuming you would have called it when player is killed but I didn't see where you did that. Again, I could have just missed where you did that.

AddDeath is being called in the code when the project is built, run, and the player kills themself in game. Currently with the test dummies in the test level, the game isn't picking them up as valid kills, but when the player kills themself it is picked up as a valid death, so without going out of scope for this to fix picking up the test dummies as actual kills, the test coverage code was able to be called within addDeath.

**Comment by MMercer8989** [comment]
> 
> 
> > > > So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.
> > > 
> > > 
> > > In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.
> > 
> > 
> > Right, I saw the comment, I guess I was more wondering where 'AddDeath' is being called outside of the coverage tests. I'm assuming you would have called it when player is killed but I didn't see where you did that. Again, I could have just missed where you did that.
> 
> AddDeath is being called in the code when the project is built, run, and the player kills themself in game. Currently with the test dummies in the test level, the game isn't picking them up as valid kills, but when the player kills themself it is picked up as a valid death, so without going out of scope for this to fix picking up the test dummies as actual kills, the test coverage code was able to be called within addDeath.

Okay, that might be a change to consider then, seeing as how the test dummy should register as a valid kill. I don't think a change like that would be out of scope. So I apologize for any confusion, like I said though, your current changes look good so you have my approval.

**Comment by mryindles** [comment]
> > > > > So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.
> > > > 
> > > > 
> > > > In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.
> > > 
> > > 
> > > Right, I saw the comment, I guess I was more wondering where 'AddDeath' is being called outside of the coverage tests. I'm assuming you would have called it when player is killed but I didn't see where you did that. Again, I could have just missed where you did that.
> > 
> > 
> > AddDeath is being called in the code when the project is built, run, and the player kills themself in game. Currently with the test dummies in the test level, the game isn't picking them up as valid kills, but when the player kills themself it is picked up as a valid death, so without going out of scope for this to fix picking up the test dummies as actual kills, the test coverage code was able to be called within addDeath.
> 
> Okay, that might be a change to consider then, seeing as how the test dummy should register as a valid kill. I don't think a change like that would be out of scope. So I apologize for any confusion, like I said though, your current changes look good so you have my approval.

To clarify, testdummy in my previous comment refers to the current actors open tournament has placed within the test level, NOT my variable I created call testDummy. So what I mean is my testDummy variable DOES recognize addKill as valid, and does correctly add kills, but if you MANUALLY go and shoot the test dummies in the open tournament test level, and "kill" them they DO NOT register as a valid kill.

**Comment by MMercer8989** [comment]
> 
> 
> > > > > > So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.
> > > > > 
> > > > > 
> > > > > In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.
> > > > 
> > > > 
> > > > Right, I saw the comment, I guess I was more wondering where 'AddDeath' is being called outside of the coverage tests. I'm assuming you would have called it when player is killed but I didn't see where you did that. Again, I could have just missed where you did that.
> > > 
> > > 
> > > AddDeath is being called in the code when the project is built, run, and the player kills themself in game. Currently with the test dummies in the test level, the game isn't picking them up as valid kills, but when the player kills themself it is picked up as a valid death, so without going out of scope for this to fix picking up the test dummies as actual kills, the test coverage code was able to be called within addDeath.
> > 
> > 
> > Okay, that might be a change to consider then, seeing as how the test dummy should register as a valid kill. I don't think a change like that would be out of scope. So I apologize for any confusion, like I said though, your current changes look good so you have my approval.
> 
> To clarify, testdummy in my previous comment refers to the current actors open tournament has placed within the test level, NOT my variable I created call testDummy. So what I mean is my testDummy variable DOES recognize addKill as valid, and does correctly add kills, but if you MANUALLY go and shoot the test dummies in the open tournament test level, and "kill" them they DO NOT register as a valid kill.

okay, thank you, I suppose that makes sense in the context of what you are working on then. I know in my case I have it printing off that information for killing test dummies but my work also wasn't heavily dependent on the actual kill count.

**Review by daniellcurto — COMMENTED** [review]
I cannot approve this without having any kind of test coverage.

**Comment by mryindles** [comment]
> I cannot approve this without having any kind of test coverage.

Including a folder with a screenshot of test coverage actually running, please standby.

**Comment by mryindles** [comment]
> > > > > > > So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.
> > > > > > 
> > > > > > 
> > > > > > In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.
> > > > > 
> > > > > 
> > > > > Right, I saw the comment, I guess I was more wondering where 'AddDeath' is being called outside of the coverage tests. I'm assuming you would have called it when player is killed but I didn't see where you did that. Again, I could have just missed where you did that.
> > > > 
> > > > 
> > > > AddDeath is being called in the code when the project is built, run, and the player kills themself in game. Currently with the test dummies in the test level, the game isn't picking them up as valid kills, but when the player kills themself it is picked up as a valid death, so without going out of scope for this to fix picking up the test dummies as actual kills, the test coverage code was able to be called within addDeath.
> > > 
> > > 
> > > Okay, that might be a change to consider then, seeing as how the test dummy should register as a valid kill. I don't think a change like that would be out of scope. So I apologize for any confusion, like I said though, your current changes look good so you have my approval.
> > 
> > 
> > To clarify, testdummy in my previous comment refers to the current actors open tournament has placed within the test level, NOT my variable I created call testDummy. So what I mean is my testDummy variable DOES recognize addKill as valid, and does correctly add kills, but if you MANUALLY go and shoot the test dummies in the open tournament test level, and "kill" them they DO NOT register as a valid kill.
> 
> okay, thank you, I suppose that makes sense in the context of what you are working on then. I know in my case I have it printing off that information for killing test dummies but my work also wasn't heavily dependent on the actual kill count.

Yeah, sadly the original game devs didn't really implement the kill count incrementing when you kill the test dummies in the test level. AddKill properly works in my test coverage, so we know its not a problem with that function, and all of my code executes perfectly in test coverage so we know the code I've written is fine as well. I'm fine with working to properly increment kill count on killing dummies, it's just out of scope for this branch imo, as this branch does what it's supposed to, and includes test coverage independent of any specific test map to back it up.

**Comment by MMercer8989** [comment]
> 
> 
> > > > > > > > So, I don't have many complaints about the work here, maybe just a few nitpicks. The calls to 'AddKill' in your coverage test could have been implemented as a couple of for loops, though that's more food for thought on ways to organize the code. I am curious however, and maybe I missed this but where is 'AddDeath' being called? Other than that, I would say that this is fine work.
> > > > > > > 
> > > > > > > 
> > > > > > > In the test coverage code at the end, there is a comment mentioning that originally this block of coverage code was being called within the add death function, so after the test coverage function exited a death would be added within the AddDeath function, and as an exit condition a shutdown message would be displayed. By default AddDeath was not called within the test coverage function, but it easily could be implemented within there by future developers.
> > > > > > 
> > > > > > 
> > > > > > Right, I saw the comment, I guess I was more wondering where 'AddDeath' is being called outside of the coverage tests. I'm assuming you would have called it when player is killed but I didn't see where you did that. Again, I could have just missed where you did that.
> > > > > 
> > > > > 
> > > > > AddDeath is being called in the code when the project is built, run, and the player kills themself in game. Currently with the test dummies in the test level, the game isn't picking them up as valid kills, but when the player kills themself it is picked up as a valid death, so without going out of scope for this to fix picking up the test dummies as actual kills, the test coverage code was able to be called within addDeath.
> > > > 
> > > > 
> > > > Okay, that might be a change to consider then, seeing as how the test dummy should register as a valid kill. I don't think a change like that would be out of scope. So I apologize for any confusion, like I said though, your current changes look good so you have my approval.
> > > 
> > > 
> > > To clarify, testdummy in my previous comment refers to the current actors open tournament has placed within the test level, NOT my variable I created call testDummy. So what I mean is my testDummy variable DOES recognize addKill as valid, and does correctly add kills, but if you MANUALLY go and shoot the test dummies in the open tournament test level, and "kill" them they DO NOT register as a valid kill.
> > 
> > 
> > okay, thank you, I suppose that makes sense in the context of what you are working on then. I know in my case I have it printing off that information for killing test dummies but my work also wasn't heavily dependent on the actual kill count.
> 
> Yeah, sadly the original game devs didn't really implement the kill count incrementing when you kill the test dummies in the test level. AddKill properly works in my test coverage, so we know its not a problem with that function, and all of my code executes perfectly in test coverage so we know the code I've written is fine as well. I'm fine with working to properly increment kill count on killing dummies, it's just out of scope for this branch imo, as this branch does what it's supposed to, and includes test coverage independent of any specific test map to back it up.

sounds good,  again, I apologize for any confusion this may have stirred up

**Review by daniellcurto — APPROVED** [review]
Sweet, everything looks like it is fully operational. Nice job Matt.  I see you have worked really hard on this project.

**Pull request merged**
