### PR TITLE
Death messages

### PR DESCRIPTION
**Pull request by MMercer8989**
This Pull request features all of my changes for the death messages update. The commits you will find here are split between commits for the ordinary death message functionality and the death messages coverage test. For each of the commits I have made sure to provide a detailed description so that there is no confusion for what is being done. If there are any questions, remarks, or statements make sure to put them in the comments below.

### CODE REVIEW

**Review by mryindles — APPROVED** [review]
I really like the logic, and find the messages quite humorous fitting the same vein of most death messages for arena shooters like the other unreal tournament games, Halo, etc. Only 2 questions I had, did you update design.md in this branch to include your changes made on this branch? Or did you include that in the previous documentation pull? Secondly, I don't know if we need a comment above the include statements, as the original devs never made a comment above their include statements stating why they needed them, but that's more of a nitpicky design question. Either way this code is completely good to merge into master, I really like the messages.

**Comment by MMercer8989** [comment]
> 
> 
> I really like the logic, and find the messages quite humorous fitting the same vein of most death messages for arena shooters like the other unreal tournament games, Halo, etc. Only 2 questions I had, did you update design.md in this branch to include your changes made on this branch? Or did you include that in the previous documentation pull? Secondly, I don't know if we need a comment above the include statements, as the original devs never made a comment above their include statements stating why they needed them, but that's more of a nitpicky design question. Either way this code is completely good to merge into master, I really like the messages.

I did not update design.md here as my branch was a bit behind master, I do plan to update it in the next day or so. Understandable nitpick, I'll probably leave it in though as it is a minor change and is not taking anything away from the code. Thank you for the great feedback by the way, Ryan.

**Review by daniellcurto — COMMENTED** [review]
I do not see any way of testing to make sure everything is working properly. Thus, I cannot approve it just yet.

**Review by daniellcurto — APPROVED** [review]
Everything looks like it is in order. Good job guys.

**Comment by MMercer8989** [comment]
> 
> 
> I do not see any way of testing to make sure everything is working properly. Thus, I cannot approve it just yet.

If you had read my last pull request then you would know that the screen shot was included in that one. Additionally, I explain in some of the last commit messages / code how to use the test function.

**Pull request merged**
